version: '3'
services:
  db:
    image: mysql:8.0.19
    container_name: db-server
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
    - 3306:3306
    volumes:
    - /Users/daiyu/dev/data/mysql-data:/var/lib/mysql
