version: '3'
services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.5.2
    container_name: artifactory
    ports:
    - 9091:8081
    volumes:
    - jfrog_artifactory_data:/var/opt/jfrog/artifactory
    #    Add extra Java options by uncommenting the following lines
    #    environment:
    #     - EXTRA_JAVA_OPTIONS=-Xmx4g
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000

volumes:
  jfrog_artifactory_data:
    external:
      name: dockercompose_artifactory_data
